# typed: false
# frozen_string_literal: true

# This file was generated by the Homebrew formula generator
class SafeChainAgent < Formula
  desc "Aikido SafeChain Agent"
  homepage "https://github.com/AikidoSec/safechain-agent"
  version "0.1.0"
  license "AGPL"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AikidoSec/safechain-agent/releases/download/v#{version}/safechain-agent-darwin-amd64"
      sha256 "913301163bcae37cd8eadf54e7afd8491b23ca909fc5583c914d922ed6f1627b"
    end
    if Hardware::CPU.arm?
      url "https://github.com/AikidoSec/safechain-agent/releases/download/v#{version}/safechain-agent-darwin-arm64"
      sha256 "af58a3238df3bd8059564ac3f3698e323f908831fd24b8f78bf72f44f1cc96d8"
    end
  end

  def install
    # Install Aikido Agent binary
    binary_name = Hardware::CPU.intel? ? "safechain-agent-darwin-amd64" : "safechain-agent-darwin-arm64"
    downloaded_file = if File.exist?(binary_name)
      binary_name
    elsif (file = Dir.glob("*").find { |f| File.file?(f) && File.executable?(f) })
      file
    else
      raise "Could not find downloaded binary file"
    end
    bin.install downloaded_file => "safechain-agent"
    chmod 0755, bin/"safechain-agent"
  end

  service do
    name macos: "com.aikidosecurity.safechainagent"
    run [opt_bin/"SafeChainAgent"]
    run_at_load true
    keep_alive true
    log_path var/"log/SafeChainAgent.log"
    error_log_path var/"log/SafeChainAgent.error.log"
  end

  test do
    system "#{bin}/SafeChainAgent", "--version"
  end
end

